from .core.teletypes import *  # NOQA
from .core.teletypes import inline_query_result


InlineQueryResultArticle = inline_query_result.Article
InlineQueryResultAudio = inline_query_result.Audio
InlineQueryResultCachedAudio = inline_query_result.CachedAudio
InlineQueryResultCachedDocument = inline_query_result.CachedDocument
InlineQueryResultCachedGif = inline_query_result.CachedGif
InlineQueryResultCachedMpeg4Gif = inline_query_result.CachedMpeg4Gif
InlineQueryResultCachedSticker = inline_query_result.CachedSticker
InlineQueryResultCachedVideo = inline_query_result.CachedVideo
InlineQueryResultCachedVoice = inline_query_result.CachedVoice
InlineQueryResultContact = inline_query_result.Contact
InlineQueryResultDocument = inline_query_result.Document
InlineQueryResultGame = inline_query_result.Game
InlineQueryResultGif = inline_query_result.Gif
InlineQueryResultLocation = inline_query_result.Location
InlineQueryResultMpeg4Gif = inline_query_result.Mpeg4Gif
InlineQueryResultPhoto = inline_query_result.Photo
InlineQueryResultVenue = inline_query_result.Venue
InlineQueryResultVideo = inline_query_result.Video
InlineQueryResultVoice = inline_query_result.Voice
