from .base import TelegramStructure
from .user import User
from .chat import Chat
from .audio import Audio
from .document import Document
from .game import Game
from .sticker import Sticker
from .video import Video
from .voice import Voice
from .contact import Contact
from .location import Location
from .venue import Venue
from .message_entity import MessageEntity
from .photo_size import PhotoSize
