name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository # You must checkout your repository first.
        uses: actions/checkout@v3

      - name: Publish Package
        uses: celsiusnarhwal/poetry-publish@v2
        with:
          python-version: 3.11
          poetry-version: 1.3.1
          token: ${{ secrets.PYPI_TOKEN }}
          build: true
